src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 * @Vich\Uploadable
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @Vich\UploadableField(mapping="article_cover", fileNameProperty="cover")
     * @var File|null
     */
    private $file;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cover;

    /**
     * @ORM\Column(type="boolean")
     */
    private $published;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="article", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="articles")
     */
    private $category;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }
    public function getFile(): ?File
    {
        return $this->file;
    }

    
    public function setFile(?File $file = null): self
    {
        $this->file = $file;

           return $this; 
        
    }

    

    

    public function getCover(): ?string
    {
        return $this->cover;
    }

    public function setCover(?string $cover): self
    {
        $this->cover = $cover;

        return $this;
    }

    public function getPublished(): ?bool
    {
        return $this->published;
    }

    public function setPublished(bool $published): self
    {
        $this->published = $published;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdated(): ?\DateTimeInterface
    {
        return $this->updated;
    }

    public function setUpdated(?\DateTimeInterface $updated): self
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\ArticleRepository;
use App\Entity\Article;

class MainController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function home(ArticleRepository $articleRepository): Response
    {
        $listArticles = $articleRepository->findPublishedArticle();
        return $this->render('front/main/home.html.twig', [
            'articles' => $listArticles,
        ]);
    }

    

    /**
     * @Route("/cgu", name="cgu")
     */
    public function cgu(): Response
    {
        // Nous générons la vue de la page des mentions légales
        return $this->render('front/main/cgu.html.twig');
    }

    /**
     * @Route("/mentions-legales", name="mentions-legales")
     */
    public function mentionsLegales(): Response
    {
        // Nous générons la vue de la page des mentions légales
        return $this->render('front/main/mentions-legales.html.twig');
    }
}

templates/front/main/cgu.html.twig
{% extends 'front/layout.html.twig' %}

{% block title %}CGU{% endblock %}

{%block stylesheets %}
{{ parent() }}
{% endblock %}

{% block content %}

    <h1>Conditions générales d'utilisation</h1>
    <p> Duis pretium ipsum lectus, eget convallis tortor tempor eu. Praesent urna sem, vulputate ut euismod id, finibus venenatis odio. Sed in bibendum felis. Ut ac efficitur sem, sed tristique lorem. Fusce tristique cursus nulla nec luctus. In porta tortor eu dui vestibulum blandit. Sed sit amet dui mollis, tempus nulla in, gravida urna. Integer quis pulvinar turpis. Aliquam libero justo, tempor nec tortor id, porttitor malesuada lacus.

Sed id odio a nibh faucibus vehicula. Morbi feugiat quam sed neque dignissim blandit. Integer interdum justo nulla. Sed consequat, lectus et venenatis pharetra, diam felis fermentum neque, viverra porta sem est ut sem. Suspendisse a enim pretium, volutpat sem vel, maximus ipsum. Nullam eleifend quam vitae eros rutrum, vitae vulputate augue fringilla. Integer accumsan ultricies lacus vitae facilisis. Curabitur cursus dui aliquet purus dignissim rhoncus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras nisi lectus, maximus vel vehicula vel, venenatis vel nunc. Aliquam accumsan blandit diam. Nullam tincidunt ex ac erat eleifend posuere. Quisque lorem lacus, ultrices at tellus ut, vulputate ornare nisi. Nam ac iaculis sapien.

Mauris quis magna eu quam feugiat fermentum. Suspendisse arcu erat, viverra mattis euismod sit amet, pulvinar id ipsum. Aliquam arcu velit, lacinia eget laoreet vel, viverra ut libero. Donec blandit varius elit, nec rhoncus nibh pulvinar in. Sed varius justo augue. Nam vehicula magna quam, eu vulputate nisl viverra eget. Integer quis ipsum ut nunc scelerisque dictum. </p>
{% endblock %}

templates/front/main/home.html.twig
{% extends 'front/layout.html.twig' %}

{% block title %}Mon blog{% endblock %}

{%block stylesheets %}
{{ parent() }}
{% endblock %}

{% block content %}
<h1 class='title'>Mon Blog</h1>



     

        
{% for article in articles %}
           
                <div class='article'>
                <h3>{{ article.title }}</h3>
                <p>{{ article.content |u.truncate(50, '...', false) }}</p>
                <img src="{{ vich_uploader_asset(article, 'file') }}" alt="{{ article.title }}" />
                <p>Crée le {{ article.createdAt ? article.createdAt|date('d-m-Y H:i:s') : '' }}</p>
                <p>Modifié le {{ article.updated ? article.updated|date('d-m-Y H:i:s') : '' }}</p>
                <a class="btn btn-dark" href='{{ path('showMain', {'id': article.id}) }}'>Lire la suite</a>
                </div>
                
{% endfor %}

{% endblock %}

templates/front/main/mentions-legales.html.twig
{% extends 'front/layout.html.twig' %}

{% block title %}Mentions légales{% endblock %}

{%block stylesheets %}
{{ parent() }}
{% endblock %}

{% block content %}

    <h1>Mentions légales</h1>
    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ac quam lacus. Vivamus sed massa pretium, porttitor massa in, viverra ex. Suspendisse turpis diam, finibus id maximus non, auctor vitae leo. Suspendisse accumsan nibh nisl, vehicula volutpat quam ullamcorper id. Aliquam turpis nisi, tempor nec neque ut, laoreet bibendum felis. In eu eleifend nisi, vitae aliquam justo. Integer at libero a arcu bibendum pharetra. Donec gravida risus ut libero ullamcorper, id pellentesque lacus viverra.

Phasellus tristique tortor in tortor accumsan porttitor. Suspendisse augue eros, lacinia in nunc vel, iaculis vestibulum nibh. Nulla ullamcorper in ex sed vulputate. Donec non gravida ex. Aliquam convallis euismod enim, a dictum ex tempus vel. Quisque quis massa nec lacus ornare laoreet sit amet quis sem. Maecenas eget ex hendrerit, tempor urna bibendum, blandit diam. Ut eget lacus quis arcu elementum eleifend. Donec at magna non orci bibendum lobortis vel vitae ipsum. Aenean rhoncus, lorem dictum rutrum vestibulum, risus purus iaculis diam, sed iaculis lorem metus vitae ex. Phasellus vitae suscipit metus. Ut imperdiet tortor a tortor posuere, ultrices interdum magna volutpat.

In tortor massa, malesuada non ex non, porttitor aliquet nisi. Aliquam quis nibh mollis, pharetra diam eget, ornare nisl. Proin tortor erat, aliquam nec varius ac, finibus facilisis ipsum. Pellentesque rutrum consectetur ligula, vitae iaculis sapien bibendum dictum. Sed laoreet laoreet risus, at fringilla mi hendrerit id. Praesent faucibus dui eu erat interdum, a semper eros iaculis. Integer erat velit, hendrerit sed enim non, pretium elementum lectus. Duis tempus volutpat ipsum, ac mollis dolor sagittis eget. Mauris at mi blandit, sodales tellus sit amet, interdum metus. Phasellus ut rhoncus turpis. Fusce sit amet hendrerit erat. Mauris eget sollicitudin velit. Nunc vitae nunc enim. Vestibulum faucibus nec est nec semper.

Sed ultricies sem mi, dignissim blandit velit tincidunt vel. Nulla hendrerit commodo nibh, non porttitor erat consequat a. Morbi pulvinar lorem mauris, a lobortis ipsum imperdiet nec. Aliquam erat volutpat. Nam mollis sed mauris tempor pretium. Fusce bibendum lacinia nulla. Duis ac viverra tellus.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel elementum mi, id fermentum lectus. Sed facilisis, sapien non consequat egestas, orci quam scelerisque ante, at molestie augue libero eget lacus. Sed elementum risus eu commodo placerat. Vivamus congue enim sed felis sagittis sagittis. Donec feugiat nulla in fringilla molestie. Sed ligula libero, lobortis eu odio a, sodales molestie enim. In sed luctus neque. Nulla nec metus risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent pretium, neque eget interdum eleifend, mauris odio laoreet nunc, sed dictum dui tortor nec mauris. Maecenas mi lorem, maximus id lacinia vestibulum, elementum ac felis. Vestibulum dictum hendrerit mi, ac ullamcorper quam congue nec. Etiam laoreet in magna nec finibus.

Etiam in sapien id lorem gravida efficitur eu sed lectus. In lobortis hendrerit justo ac gravida. Quisque id semper tortor. Donec tortor justo, blandit quis erat at, blandit tempus lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur vel sapien tincidunt dui tempus ullamcorper. Suspendisse ultrices quis tortor ut aliquam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer dolor velit, laoreet sagittis feugiat at, posuere ac ex.

Nam at nibh rhoncus lorem semper posuere et sit amet lacus. Quisque ornare lacus lobortis elit interdum sodales. Pellentesque tempus varius tellus, eu convallis erat accumsan eu. Sed eleifend tempus ipsum eget hendrerit. Nunc quis consequat purus. Mauris ut placerat neque. Fusce efficitur purus in magna faucibus tristique. Nam eros diam, pharetra at augue eu, bibendum commodo quam. Integer rhoncus eu lectus vitae eleifend. </p>
{% endblock %}

templates/front/main/show.html.twig
{% extends 'front/layout.html.twig' %}

{% block title %}{{article.title}}{% endblock %}
{% block content %}
 <div>
                <h3>{{ article.title }}</h3>
                <p>{{ article.content }}</p>
                <div>{{ article.cover }}</div>
                <p>Crée le {{ article.createdAt ? article.createdAt|date('d/m/Y H:i:s') : '' }}</p>
                <p>Modifié le {{ article.updated ? article.updated|date('d/m/Y H:i:s') : '' }}</p>
                <p>Catégorie : {{ article.category ? article.category.name : 'Non classé' }} </p>
                </div>

                <h4>Commentaires</h4>
                <div>
                {% for comment in article.comments %}
                    <p>{{ comment.username ~ ' - ' ~ comment.createdAt|date('d/m/Y H:i:s')  }}</p>
                    <p>{{ comment.content }}</p>
                {% endfor %}
                </div>

    {{ include('front/comment/_form.html.twig') }}

        <a class="btn btn-dark" href="{{ path('home')}}">Retour</a>    
{% endblock %}